// <auto-generated />
using JSJMExoticCarsWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JSJMExoticCarsWebApp.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20230508105310_create database")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JSJMExoticCarsWebApp.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("car_brand");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("car_model");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("car_description");

                    b.Property<int>("Fuel")
                        .HasColumnType("int")
                        .HasColumnName("car_fuel_type");

                    b.Property<int>("Mileage")
                        .HasColumnType("int")
                        .HasColumnName("car_mileage");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("car_price");

                    b.Property<int>("Transmission")
                        .HasColumnType("int")
                        .HasColumnName("car_transmission_type");

                    b.Property<int>("YearModel")
                        .HasColumnType("int")
                        .HasColumnName("car_year_model");

                    b.HasKey("Id");

                    b.ToTable("CarTable");
                });
#pragma warning restore 612, 618
        }
    }
}
